# Generated by Django 5.0.4 on 2024-05-01 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Investimento", models.TextField(max_length=255)),
                ("valor", models.FloatField()),
                ("pago", models.BooleanField(default=False)),
                ("data", models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
